 export const indianCities = [
    // Tier 1 Cities
    { city: "Delhi", state: "Delhi" },
    { city: "Mumbai", state: "Maharashtra" },
    { city: "Bengaluru", state: "Karnataka" },
    { city: "Chennai", state: "Tamil Nadu" },
    { city: "Hyderabad", state: "Telangana" },
    { city: "Kolkata", state: "West Bengal" },
    { city: "Pune", state: "Maharashtra" },
    { city: "Ahmedabad", state: "Gujarat" },
    
    // Tier 2 Cities
    { city: "Jaipur", state: "Rajasthan" },
    { city: "Lucknow", state: "Uttar Pradesh" },
    { city: "Kanpur", state: "Uttar Pradesh" },
    { city: "Nagpur", state: "Maharashtra" },
    { city: "Indore", state: "Madhya Pradesh" },
    { city: "Bhopal", state: "Madhya Pradesh" },
    { city: "Vadodara", state: "Gujarat" },
    { city: "Surat", state: "Gujarat" },
    { city: "Rajkot", state: "Gujarat" },
    { city: "Coimbatore", state: "Tamil Nadu" },
    { city: "Madurai", state: "Tamil Nadu" },
    { city: "Visakhapatnam", state: "Andhra Pradesh" },
    { city: "Vijayawada", state: "Andhra Pradesh" },
    { city: "Mysuru", state: "Karnataka" },
    { city: "Mangaluru", state: "Karnataka" },
    { city: "Thiruvananthapuram", state: "Kerala" },
    { city: "Kochi", state: "Kerala" },
    { city: "Patna", state: "Bihar" },
    { city: "Ranchi", state: "Jharkhand" },
    { city: "Jamshedpur", state: "Jharkhand" },
    { city: "Bhubaneswar", state: "Odisha" },
    { city: "Cuttack", state: "Odisha" },
    { city: "Chandigarh", state: "Chandigarh" },
    { city: "Ludhiana", state: "Punjab" },
    { city: "Amritsar", state: "Punjab" },
    { city: "Dehradun", state: "Uttarakhand" },
    { city: "Guwahati", state: "Assam" },
    { city: "Agra", state: "Uttar Pradesh" },
    { city: "Varanasi", state: "Uttar Pradesh" },
    { city: "Meerut", state: "Uttar Pradesh" },
    { city: "Noida", state: "Uttar Pradesh" },
    { city: "Ghaziabad", state: "Uttar Pradesh" },
    { city: "Faridabad", state: "Haryana" },
    { city: "Gurugram", state: "Haryana" },
    { city: "Nashik", state: "Maharashtra" },
    { city: "Aurangabad", state: "Maharashtra" },
    { city: "Tiruchirappalli", state: "Tamil Nadu" },
    { city: "Jodhpur", state: "Rajasthan" },
    { city: "Udaipur", state: "Rajasthan" },
    { city: "Allahabad", state: "Uttar Pradesh" },
    { city: "Gwalior", state: "Madhya Pradesh" },
    { city: "Jabalpur", state: "Madhya Pradesh" },
    { city: "Salem", state: "Tamil Nadu" },
    { city: "Hubli-Dharwad", state: "Karnataka" },
    { city: "Guntur", state: "Andhra Pradesh" },
    { city: "Warangal", state: "Telangana" },
    { city: "Kozhikode", state: "Kerala" },
    { city: "Thrissur", state: "Kerala" },
    { city: "Srinagar", state: "Jammu & Kashmir" },
    { city: "Shimla", state: "Himachal Pradesh" }
  ];
  